version: '3.8'

services:
  # 1. Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mysql
    # This command starts a temporary local server for development
    command: php artisan serve --host=0.0.0.0 --port=8000

  # 2. React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network

  # 3. MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test_root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # 4. phpMyAdmin (Database Management Graphic Interface)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_gui
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: